### ISSUE TITLE
[PE-D][Tester E] The net amount changes with the application of the command "View"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-1/tp#233]
![image.png](https://raw.githubusercontent.com/zbz-lvlv/ped/main/files/d0e23f22-a699-4bad-9bd2-6d0d48420c4f.png)

I'm not sure if this is intended behavior, but I believe that the net amount is meant to give the net earnings in total. As such, I don't think it should change with filtering of contacts.

Remedy: Make the net amount always reflect the total net amount of all clients.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zbz-lvlv/ped#4

**Comment by ElginL** [comment]
This is an intended behavior. The `net amount` reflects the overall `gains/losses` according to the clients that are currently listed in the panel. As such, when you use the `view` command, you will be seeing the `gains/losses` specific to that particular client. Which is a very useful functionality since you can tell how profitable your business is with a particular client, and not only overall.
